name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build binary
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          artifact_name: check-docker
          asset_name: check-docker-x86_64-unknown-linux-gnu
          use_cross: false
        - os: ubuntu-latest
          target: aarch64-unknown-linux-gnu
          artifact_name: check-docker
          asset_name: check-docker-aarch64-unknown-linux-gnu
          use_cross: true

        - os: macos-latest
          target: x86_64-apple-darwin
          artifact_name: check-docker
          asset_name: check-docker-x86_64-apple-darwin
          use_cross: false

        - os: macos-latest
          target: aarch64-apple-darwin
          artifact_name: check-docker
          asset_name: check-docker-aarch64-apple-darwin
          use_cross: false

        - os: windows-latest
          target: x86_64-pc-windows-msvc
          extension: .exe
          asset_name: check-docker-x86_64-pc-windows-msvc
          use_cross: false

        # - os: windows-latest-arm64
        #   target: aarch64-pc-windows-msvc
        #   extension: .exe
        #   asset_name: check-docker-aarch64-pc-windows-msvc


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: build
          args: --release --target ${{ matrix.target }} --manifest-path check-docker/Cargo.toml
      - name: rename artifact
        run: mv check-docker/target/${{ matrix.target }}/release/check-docker${{ matrix.extension }} check-docker/${{ matrix.asset_name }}${{ matrix.extension }}
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            check-docker/${{ matrix.asset_name }}${{ matrix.extension }}



# steps:
# - name: Checkout repository
#   uses: actions/checkout@v4

# # Rust環境の構築
# - name: Rust環境の構築
#   uses: actions-rs/toolchain@v1
#   with:
#     toolchain: stable
#     override: true
